# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

web:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200,http://localhost:5173,https://literandltx.github.io"
  cookie:
    secure: true
    same-site: None

app:
  rate-limit:
    cache-max-size: 10000
    cache-expire: 5m
    bucket-capacity: 20
    refill-interval: 1m
