spring:
  application:
    name: timer-backend-spring
  profiles:
    default: dev

server:
  port: 8080
  forward-headers-strategy: framework

jwt:
  refresh:
    expiration: 604800000
  expiration: 900000
  secret: secretsecretsecretsecretsecretsecret

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
      roles: ADMIN

app:
  init:
    admin-email: "admin_default@timer.com"
    default-admin-password: ${APP_ADMIN_PASSWORD:DefaultSecureAdminPassword123!}
  rate-limit:
    cache-max-size: 1000
    cache-expire: 5m
    bucket-capacity: 20
    refill-interval: 1m
